name: Run Pester Tests

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Pester
        run: Install-Module -Name Pester -Force -SkipPublisherCheck
        shell: pwsh

      - name: Run Pester tests
        run: |
          pwsh -NoProfile -Command "Invoke-Pester -Path 'Tests/PSDataNormalizer.Tests.ps1' -Output Detailed"
        shell: pwsh
